apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountkey: your-base64-encoded-storage-account-name-here
  azurestorageaccountname: your-base64-encoded-storage-key-name-here

